### ISSUE TITLE
打开SVG图片乱码，显示不全面

### ISSUE THREAD

**Issue by adminpython** [jark006/jarkViewer#5]
打开乱码![微信截图_20241022091742](https://github.com/user-attachments/assets/d37d1993-dd67-4793-b85c-ae60667e5fbb)

**Comment by jark006** [comment]
目前svg解码用的是lunasvg，这个库对svg的特性支持确实不全面，我再找找其他svg库

**Comment by jark006** [comment]
刚更新了lunasvg库，我测试支持更多svg特性了，你用最新版 v1.20 再试试
