### ISSUE TITLE
建议 查看图片时，能不能去掉窗口上面的标题栏

### ISSUE THREAD

**Issue by Firfr** [jark006/jarkViewer#7]
感谢大佬的软件
查看图片时，能不能去掉窗口上面的标题栏
像下图一样，去掉多余的边框，更简洁，
可以给图片加上一个简单边框或者增加一个阴影

![2024-11-06_20-55-12](https://github.com/user-attachments/assets/4d655bd8-b929-4d11-8e52-503287ef3c8b)

**Comment by jark006** [comment]
窗口暂时不考虑无边框，图片可以加个线条边框
