### ISSUE TITLE
请问有删除图片关联的 bat 命令文件吗

### ISSUE THREAD

**Issue by redfieldw** [jark006/jarkViewer#9]
用了段时间还是换到qView了，我想删掉jarkViewer的右键打开方式

**Comment by jark006** [comment]
> 用了段时间还是换到qView了，我想删掉jarkViewer的右键打开方式

## 🚫 取消关联文件格式

将脚本 `associate_images_uninstall.bat` （[下载](https://github.com/jark006/jarkViewer/releases/download/v1.22/associate_images_uninstall.bat)） 右键管理员身份运行即可取消 `jarkViewer` 的关联。
